-- TASKS / USERS
ALTER TABLE tasks
ADD CONSTRAINT fk_tasks_user
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- COMMENTS / TASKS
ALTER TABLE comments
ADD CONSTRAINT fk_comments_task
FOREIGN KEY (task_id) REFERENCES tasks(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- COMMENTS / USERS
ALTER TABLE comments
ADD CONSTRAINT fk_comments_user
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- TASK_TAGS / TASKS
ALTER TABLE task_tags
ADD CONSTRAINT fk_task_tags_task
FOREIGN KEY (task_id) REFERENCES tasks(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- TASK_TAGS / TAGS
ALTER TABLE task_tags
ADD CONSTRAINT fk_task_tags_tag
FOREIGN KEY (tag_id) REFERENCES tags(id)
ON DELETE CASCADE
ON UPDATE CASCADE;